<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903130643 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sale_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price DOUBLE PRECISION NOT NULL, line_total DOUBLE PRECISION NOT NULL, sale_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A6771514A7E4868 ON sale_detail (sale_id)');
        $this->addSql('CREATE INDEX IDX_5A6771514584665A ON sale_detail (product_id)');
        $this->addSql('ALTER TABLE sale_detail ADD CONSTRAINT FK_5A6771514A7E4868 FOREIGN KEY (sale_id) REFERENCES "sale" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_detail ADD CONSTRAINT FK_5A6771514584665A FOREIGN KEY (product_id) REFERENCES "product" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sale_detail DROP CONSTRAINT FK_5A6771514A7E4868');
        $this->addSql('ALTER TABLE sale_detail DROP CONSTRAINT FK_5A6771514584665A');
        $this->addSql('DROP TABLE sale_detail');
    }
}
