<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903022924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "sale" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sale_date DATE NOT NULL, total_price DOUBLE PRECISION NOT NULL, state VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E54BC0059395C3F3 ON "sale" (customer_id)');
        $this->addSql('CREATE INDEX IDX_E54BC005B03A8386 ON "sale" (created_by_id)');
        $this->addSql('CREATE INDEX IDX_E54BC005896DBBDE ON "sale" (updated_by_id)');
        $this->addSql('ALTER TABLE "sale" ADD CONSTRAINT FK_E54BC0059395C3F3 FOREIGN KEY (customer_id) REFERENCES "customer" (id)');
        $this->addSql('ALTER TABLE "sale" ADD CONSTRAINT FK_E54BC005B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "sale" ADD CONSTRAINT FK_E54BC005896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "sale" DROP CONSTRAINT FK_E54BC0059395C3F3');
        $this->addSql('ALTER TABLE "sale" DROP CONSTRAINT FK_E54BC005B03A8386');
        $this->addSql('ALTER TABLE "sale" DROP CONSTRAINT FK_E54BC005896DBBDE');
        $this->addSql('DROP TABLE "sale"');
    }
}
