<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260903012142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "customer" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_full VARCHAR(125) NOT NULL, nit_ci VARCHAR(25) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_81398E09B03A8386 ON "customer" (created_by_id)');
        $this->addSql('CREATE INDEX IDX_81398E09896DBBDE ON "customer" (updated_by_id)');
        $this->addSql('ALTER TABLE "customer" ADD CONSTRAINT FK_81398E09B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "customer" ADD CONSTRAINT FK_81398E09896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "customer" DROP CONSTRAINT FK_81398E09B03A8386');
        $this->addSql('ALTER TABLE "customer" DROP CONSTRAINT FK_81398E09896DBBDE');
        $this->addSql('DROP TABLE "customer"');
    }
}
